# typed: false
# frozen_string_literal: true

# This file is generated by lion's release workflow (.github/workflows/release.yml
# renders it from .github/lion.rb.tmpl). DO NOT EDIT in the tap.
class Lion < Formula
  desc "Task-first LinkedIn CLI: profile, connections, messaging, feed, local message store"
  homepage "https://github.com/jodok/lion"
  version "1.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jodok/lion/releases/download/v1.1.2/lion_v1.1.2_darwin_arm64.tar.gz"
      sha256 "f5204b1f790058acce57363d4d7c76ea295a11c3dff9614465ce801fb1ea9d01"
    end
    if Hardware::CPU.intel?
      url "https://github.com/jodok/lion/releases/download/v1.1.2/lion_v1.1.2_darwin_amd64.tar.gz"
      sha256 "fb3058baf23c9366bf597141b7ab3858d1ca2f7313e48ffd6b19637a1ebca90f"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jodok/lion/releases/download/v1.1.2/lion_v1.1.2_linux_arm64.tar.gz"
      sha256 "3ba5729b5a17afb32b0f749104385ca0bf1da708e38196686f3ff655705920ad"
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jodok/lion/releases/download/v1.1.2/lion_v1.1.2_linux_amd64.tar.gz"
      sha256 "8665c69c7e96201b897cb6c39e135373be2363c28645b020e04bb11f8bac1129"
    end
  end

  def install
    # Homebrew extracts the tarball and changes into its single top-level
    # directory (lion_<version>_<os>_<arch>/), so the binary is right here.
    bin.install "lion"
  end

  test do
    assert_match "lion v#{version}", shell_output("#{bin}/lion version")
  end
end
