# typed: false
# frozen_string_literal: true

# This file is generated by lion's release workflow (.github/workflows/release.yml
# renders it from .github/lion.rb.tmpl). DO NOT EDIT in the tap.
class Lion < Formula
  desc "Task-first LinkedIn CLI: profile, connections, messaging, feed, local message store"
  homepage "https://github.com/jodok/lion"
  version "1.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jodok/lion/releases/download/v1.1.1/lion_v1.1.1_darwin_arm64.tar.gz"
      sha256 "56cb6f10bbede28489d0f78f7da5852467f592cd8a55669680573e7460acb2b8"
    end
    if Hardware::CPU.intel?
      url "https://github.com/jodok/lion/releases/download/v1.1.1/lion_v1.1.1_darwin_amd64.tar.gz"
      sha256 "d091b3069af7ada57644fbdc5cc591cd11be4519609854bc1c566650b599d803"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jodok/lion/releases/download/v1.1.1/lion_v1.1.1_linux_arm64.tar.gz"
      sha256 "430e285ecb566b527074481edfe5f4c7f89b37ad4ea020a97c59e337edf3dabf"
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jodok/lion/releases/download/v1.1.1/lion_v1.1.1_linux_amd64.tar.gz"
      sha256 "2a578c9902677cc76f23d7e92b1ba10693c0b50c12efa45cc14f6e19ee35a53b"
    end
  end

  def install
    # Homebrew extracts the tarball and changes into its single top-level
    # directory (lion_<version>_<os>_<arch>/), so the binary is right here.
    bin.install "lion"
  end

  test do
    assert_match "lion v#{version}", shell_output("#{bin}/lion version")
  end
end
