# typed: false
# frozen_string_literal: true

# This file is generated by lion's release workflow. DO NOT EDIT.
class Lion < Formula
  desc "Task-first LinkedIn CLI: profile, connections, messaging, feed, local message store"
  homepage "https://github.com/jodok/lion"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jodok/lion/releases/download/v1.1.0/lion_v1.1.0_darwin_arm64.tar.gz"
      sha256 "a6a886254f9a747a0328d88d5e65e08445672b981fb58c407b73f7b4cc623ac5"
    end
    if Hardware::CPU.intel?
      url "https://github.com/jodok/lion/releases/download/v1.1.0/lion_v1.1.0_darwin_amd64.tar.gz"
      sha256 "b95c15a735495af05a5de678b0bbc6368c98ad5b79872074c0e3daf7f17225f4"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jodok/lion/releases/download/v1.1.0/lion_v1.1.0_linux_arm64.tar.gz"
      sha256 "39b94085e97c287bcbedfd69c135ba062ed9adcc6a18cdc739294dd09a3b5e81"
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jodok/lion/releases/download/v1.1.0/lion_v1.1.0_linux_amd64.tar.gz"
      sha256 "d764d29998a631a7d53c4c0cffa054a52b15d8281509d5cd1dac8e5a5daf570f"
    end
  end

  def install
    # Homebrew extracts the tarball and changes into its single top-level
    # directory (lion_<version>_<os>_<arch>/), so the binary is right here.
    bin.install "lion"
  end

  test do
    assert_match "lion v#{version}", shell_output("#{bin}/lion version")
  end
end
