# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nocli < Formula
  desc "Notion private API CLI"
  homepage "https://github.com/jodok/nocli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jodok/nocli/releases/download/v0.1.2/nocli_0.1.2_darwin_amd64.tar.gz"
      sha256 "5503399bdf76e0329f19bc689a667306493c308697746b4bb6cb4e6e89bfe5bb"

      define_method(:install) do
        bin.install "nocli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jodok/nocli/releases/download/v0.1.2/nocli_0.1.2_darwin_arm64.tar.gz"
      sha256 "29354e792422bf959077383753f4fef3080e90792b6b816d36c655e30d66a906"

      define_method(:install) do
        bin.install "nocli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jodok/nocli/releases/download/v0.1.2/nocli_0.1.2_linux_amd64.tar.gz"
      sha256 "a6c0ac25d4a415d8d105f46864785653b154a141151b88e778e72e636df57bd8"
      define_method(:install) do
        bin.install "nocli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jodok/nocli/releases/download/v0.1.2/nocli_0.1.2_linux_arm64.tar.gz"
      sha256 "ffe0f8394e6cef63302f31a86abd9bd72a41b3a9791a54a2314c62f9e21abc3a"
      define_method(:install) do
        bin.install "nocli"
      end
    end
  end

  test do
    system "#{bin}/nocli", "--help"
  end
end
