# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nocli < Formula
  desc "Notion private API CLI"
  homepage "https://github.com/jodok/nocli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jodok/nocli/releases/download/v0.1.0/nocli_0.1.0_darwin_amd64.tar.gz"
      sha256 "37f2b80e60a246d3d41711c42a5c1daac5578823f9bf7848d31a13dfe5e7020b"

      define_method(:install) do
        bin.install "nocli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jodok/nocli/releases/download/v0.1.0/nocli_0.1.0_darwin_arm64.tar.gz"
      sha256 "1571e9cd96d23936a14f9c7e347e3b345d9410d42fc8737a0b78577d815c35c9"

      define_method(:install) do
        bin.install "nocli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jodok/nocli/releases/download/v0.1.0/nocli_0.1.0_linux_amd64.tar.gz"
      sha256 "8468313279af8c81886c45ba8f055489ec70d32b96be82aa054be8e54eb72978"
      define_method(:install) do
        bin.install "nocli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jodok/nocli/releases/download/v0.1.0/nocli_0.1.0_linux_arm64.tar.gz"
      sha256 "c5813695537e185f81896b7a90599d9b168e38fa1dd55e28ec9d416533d273e6"
      define_method(:install) do
        bin.install "nocli"
      end
    end
  end

  test do
    system "#{bin}/nocli", "--help"
  end
end
